name = "SossSymPy"
uuid = "fe929fd2-ca64-4fe4-80e3-87f438d85def"
authors = ["Chad Scherrer"]
version = "0.1.0-DEV"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
